---
- hosts: localhost
  become: yes

  vars :
    csv_filename: /tmp/x_output.csv
    output_file: /tmp/x_output.xlsx
    db_name: "Manageiq"
    table_name: "inventaire"
    ColumnsName: "TypeOperation, email, DateOperation"
    ansible_python_interpreter: /usr/bin/python3
    email: abdelali.bendra@socgen.com 
    DateOperation_start :  '2023-06-04'
    DateOperation_end: '2023-06-09'

  tasks:
   
    - name: include postgress download file
      include_tasks: download.yml

    - name: include postgress  configure file
      include_tasks: postgres.yml  

    - name: insert into table
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        query: "INSERT INTO {{table_name}} ({{ ColumnsName }}) VALUES ( 'Install java ' , '{{ email }}', now())"
      become_user: postgres
 
    - name: Copy data to  CSV file
      community.postgresql.postgresql_copy:
        db: "{{ db_name }}"
        src: >
            SELECT * FROM {{ table_name }}
            WHERE DateOperation >= '{{ DateOperation_start }}'
            AND DateOperation <= '{{ DateOperation_end }}'
        copy_to: "{{ csv_filename }}"
        options:
          format: csv
          delimiter: ','
          header: true
      become_user: postgres
    
    - name: Convert CSV to XLS
      command: python3 csv_to_excel.py  "{{ csv_filename }}" "{{ output_file }}"

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted 

