- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql

# - name: "Create app database"
#   postgresql_db:
#     state: present
#     name: "{{ db_name }}"
#   become_user: postgres


- name: "Add lines to pg_hba.conf"
  blockinfile:
    path: "/var/lib/pgsql/data/pg_hba.conf"
    block: |
      # Add the following lines at the end of the file
      host    all         127.0.0.1/32    trust
      host    all         postgres       ::1/128         trust
  become: true
  become_user: postgres
  check_mode: true
  changed_when: false
  notify: restart postgres
  



# - name: "Add some dummy data to our database"
#   become_user: postgres
#   shell: psql {{ db_name }} < /tmp/dump.sql