#!/usr/bin/env groovy
pipeline {
    agent any
   

    environment {
        ACR_REPO_URL = 'microservicesb.azurecr.io'
        IMAGE_TAG = "1.1.${BUILD_NUMBER}"                   
   }

  stages {
             
        stage(' build image ') {
            steps {
                script {
                    echo "building the docker image..."

                    // sh " docker build -t microservicesb.azurecr.io/cartservice:${IMAGE_TAG} ./src/cartservice/src/ " 
                    
                    }
                
            }
        }

        stage('SonarQube Analysis') {
            steps{
                script {
                    
                    def scannerHome = tool 'sonar-scanner';

                    withSonarQubeEnv('sonarqube') {

                    sh " ${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=cartservice \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://sonarqube:9000 \
                        -Dsonar.token=sqp_62726bcc63c3a52dcecd38d9e157d0b55e9f7b65"
                    
                    } 
                }
            }
        }
        
        stage(' push image to ACR ') {
            steps {
                script {
                    echo "pushing the docker image..."
                    withCredentials([usernamePassword(credentialsId: 'ACR', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        
                        sh "echo $PASS | docker login -u $USER --password-stdin ${ACR_REPO_URL}"

                        sh " docker push  microservicesb.azurecr.io/cartservice:${IMAGE_TAG} . " 
    
                    }
                }
            }
        }
  
        
    
        stage('trriger ArgoCD application') {

        steps {
            script {
               withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'PASS', usernameVariable: 'USER')]){ 
                
                //git config here for the first time run
                sh 'git config --global user.email "jenkins@jenkins.com"'
                sh 'git config --global user.name "jenkins"'  

                sh ' [ -d "Microservice-Automated-Deployment-to-kubernetes-Cluster" ] && \
                     (cd Microservice-Automated-Deployment-to-kubernetes-Cluster && git pull) || \
                     git clone https://${USER}:${PASS}@github.com/${USER}/Microservice-Automated-Deployment-to-kubernetes-Cluster.git '
                
                sh 'sed -i "s/\\(tag: \\).*/\\1\\"$IMAGE_TAG\\"/" Microservice-Automated-Deployment-to-kubernetes-Cluster/charts/microservices/values/cartservice.yaml '
                
                sh "git remote set-url origin https://${USER}:${PASS}@github.com/${USER}/Microservice-Automated-Deployment-to-kubernetes-Cluster.git "
                
                sh 'cd Microservice-Automated-Deployment-to-kubernetes-Cluster && \
                    git add charts/microservices/values/cartservice.yaml && \
                    git commit -am "Update tag in  cartservice.yaml  with $IMAGE_TAG  " && \
                    git push origin HEAD:main ' 
                 
            }        
        
                }
            }
        }




}
}
